# -*- coding: utf-8 -*-
"""
/***************************************************************************
 KartoKlick
                                 A QGIS plugin
 kliclkt Karte
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-11-29
        copyright            : (C) 2021 by testCOmpany
        email                : test@company.de
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load KartoKlick class from file KartoKlick.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Karto_klick import KartoKlick
    return KartoKlick(iface)
